### ISSUE TITLE
Commit message on slack seems broken

### ISSUE THREAD

**Issue by sakura2uuu** [baijunyao/action-slack-notify#7]
![image](https://user-images.githubusercontent.com/11549926/101152809-8ae4ac80-365e-11eb-8a55-8d73e0ce258e.png)

**Comment by baijunyao** [comment]
Thanks, fixed, please update to v3.0.2

**Comment by baijunyao** [comment]
Thanks, fixed, please update to v3.0.2

**Comment by sakura2uuu** [comment]
@baijunyao thanks a lot
